# Generated by Django 4.1.7 on 2023-07-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_socials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='socials',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='socials_id',
            field=models.CharField(default='a', max_length=128),
        ),
    ]
