# Generated by Django 4.2.3 on 2023-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_socials_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='socials',
            field=models.IntegerField(default=0),
        ),
    ]
