# Generated by Django 4.2.3 on 2023-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='placeholder',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
