# Generated by Django 4.2.3 on 2023-07-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_input_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='content',
        ),
    ]
