# Generated by Django 4.2.3 on 2023-07-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_remove_input_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='placeholder',
            new_name='placeholding',
        ),
    ]
